version: '3.7'

services:
  node:
    image: "node:12-slim"
    container_name: nodeapp
    working_dir: /home/node/app
    environment:
      - NODE_ENV=local
      - PORT=8080
      # Set environment variable used by dd-trace library
      - DD_AGENT_HOST=datadog-agent # container_name for agent
      - DD_TRACE_AGENT_PORT=8126 # default port for APM
      # Set environment variable used by node-dogstatsd library
      - DD_STATSD_AGENT_PORT=8125 # default for statsd
    volumes:
      - ./app:/home/node/app
    ports:
      - 8080:8080
    expose:
      - "8080"
    command: "node ."
    depends_on:
      datadog:
        condition: service_started
    networks:
      - my-net

  datadog:
    container_name: datadog-agent
    image: datadog/agent:latest
    environment:
      ## GLOBALS
      - DD_API_KEY # The value will be taken from the .env file
      - DD_SITE # The value will be taken from the .env file
      - DD_HOSTNAME=localpro
      - DD_TAGS=env:local owner:petems
      - DD_AC_EXCLUDE=name:datadog-agent # exclude this container from data collection
      ## APM https://docs.datadoghq.com/agent/docker/apm/
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      ## LOGS https://docs.datadoghq.com/agent/docker/log/
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      ## LIVE PROCESSES https://docs.datadoghq.com/graphing/infrastructure/process/?tab=docker
      - DD_PROCESS_AGENT_ENABLED=true
      ## DOGSTATSD
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    ports:
      - 8126:8126/tcp # APM available from any host
      - 8125:8125/udp # Dogstatsd
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
     - /etc/passwd:/etc/passwd:ro # LIVE PROCESSES
    networks:
      - my-net # Created with docker network create my-net and deleted with docker network rm my-net

networks:
  my-net:
    external: true
